// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htwjcyxdiufqrohrwxsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0d2pjeXhkaXVmcXJvaHJ3eHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODI2OTgsImV4cCI6MjA3NDI1ODY5OH0.VY5qFhHHcJPCjwWET6fRuPcX6fBFXX0xdPaPMSD4PiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});